list = [1, 2, 3, 4, 5, 6, 7, 3, 8, 9,3, 6, 3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  3, 3, 3, 3, 3,  10]
names = ['son', 'father', 3, 5, 'mother', 'daughter', 90, 'uncle', 'aunt', 'nephew', 'niece']

# list.insert(3, 'jiwan')
# print(list)
# names.insert(5, 'jiwan')
# print(names)
# list.pop(3)
# # print(list.pop(3))
# print(list)
# print(list.pop())
# print(list)
# list.remove(3)
# for i in list:
#     if i == 3:
#         list.remove(3)

# print(list)


# list.reverse()
# print(list)


# names.sort()
# print(names)

# names.

test_list = []
sample_text = '하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.하는 방법은 예상한 대로 동작하지 않습니다. 이유는 리스트를 순회하면서 요소를 제거하면 인덱스가 변경되어 예상대로 순회가 이루어지지 않기 때문입니다.'

for i in range(999999999999999999999999):
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    test_list.append(sample_text)
    print(test_list)

# list.remove(3)
# print(list)

# returnVal = names.index('mother')
# print(returnVal)

# list.extend([7, 5, 78, 5,78])
# print(list)

# print(list)
# list.append(7)
# print(list)

# print(list)
# list.clear()
# print(list)

# list.clear()
# list.append(7)
# print(list.count(3))


# list2 = list.copy()
# print(list) 
# print(list2) 
# list.clear()
# print(list2) 

# list.count()

# print(list.count(4))

